# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
        
    - name: Setup NuGet.exe for use with actions, include Telerik source
      # You may pin to the exact commit or the version.
      # uses: NuGet/setup-nuget@04b0c2b8d1b97922f67eca497d7cf0bf17b8ffe1
      uses: NuGet/setup-nuget@v1.0.5
      with:
          nuget-version: '5.x'
          run: nuget add source --username ${{ secrets.TELERIK_USER }} --password ${{ secrets.TELERIK_PASSWORD }} --store-password-in-clear-text --name telerik.com "https://nuget.telerik.com/nuget"
                    
    - name: Adding Telerik NuGet
      uses: NuGet/setup-nuget@v1.0.5
      with:
          run: dotnet restore
      
    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: dotnet publish Cosmos Editor
      run: dotnet publish /home/runner/work/Cosmos.Cms/Cosmos.Cms/CDT.Cosmos.Cms\CDT.Cosmos.Cms.csproj -c Release -o /home/runner/app/cosmoseditor
      
    - name: dotnet publish Cosmos Publisher
      run: dotnet publish /home/runner/work/Cosmos.Cms/Cosmos.Cms/CDT.Cosmos.Cms.Website/CDT.Cosmos.Cms.Website.csproj -c Release -o /home/runner/app/cosmospublisher

    #- name: Upload Cosmos Editor artifact for deployment job
    #  uses: actions/upload-artifact@v2
    #  with:
    #    name: Cosmos Editor Artifact
    #    path: /app/cosmoseditor
        
    #- name: Upload Cosmos Publisher artifact for deployment job
    #  uses: actions/upload-artifact@v2
    #  with:
    #    name: Cosmos Publisher Artifact
    #    path: /app/cosmospublisher
        
    # - name: Docker login
    #  run: docker login -u toiyabe -p ${{ secrets.DOCKERPASSWORD }}
        
    # - name: Build Editor Docker Image
    #  run: docker build D:\a\Cosmos.Cms\Cosmos.Cms\CDT.Cosmos.Cms
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: toiyabe
        password: ${{ secrets.DOCKERPASSWORD }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: /home/runner/app/cosmoseditor
        file: ./Dockerfile
        push: true
        tags: toiyabe/cosmoseditor:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
