name: Cosmos Common NuGet Pkg

on:
  workflow_dispatch
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./CDT.Cosmos.Cms.Common/CDT.Cosmos.Cms.Common.csproj
    - name: Build
      run: dotnet build ./CDT.Cosmos.Cms.Common/CDT.Cosmos.Cms.Common.csproj --no-restore
    #- name: Test
    #  run: dotnet test ./CDT.Cosmos.Cms.Common/CDT.Cosmos.Cms.Common.csproj --no-build --verbosity normal
    - name: Package
      run: dotnet pack -c Release -o . ./CDT.Cosmos.Cms.Common/CDT.Cosmos.Cms.Common.csproj
    - name: Publish
      run: dotnet nuget push *.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json
    
